object_preselection:
  Jet:
    pt_raw: 15
    eta: 4.7
    jetId: 0

  # same Jet for type-1 MET Correction selections as in
  # https://github.com/nurfikri89/NanoSkimmer/blob/1b4db934993267761710ab2401caf43d7a19d710/modules/AddJEC.C#L394
  # with also the JetId
  JetMuonSubtr:
    pt: 15
    EmEF: 0.9
    eta: 5.2
    jetId: 0 #6
  
  JetMuonSubtrUncorrected:
    pt: 15
    EmEF: 0.9
    eta: 5.2
    jetId: 0 #6

  JetPNetMuonSubtr:
    pt: 15
    EmEF: 0.9
    eta: 5.2
    jetId: 0 #6

  JetPNetPlusNeutrinoMuonSubtr:
    pt: 15
    EmEF: 0.9
    eta: 5.2
    jetId: 0 #6

  JetLowPtMuonSubtr:
    pt: 15
    EmEF: 0.9
    eta: 5.2

  GenJet:
    pt: 8
    eta: 10

  Muon:
    pt: 10
    eta: 2.4
    dxy: 0.045
    dz: 0.2
    id: mediumId
    iso: 0.15

  Electron:
    pt: 15
    eta: 10
    iso: 0.06
    id: mvaIso_WP80
