object_preselection:
  Jet:
    pt_raw: 15
    eta: 4.7 
    jetId: 0

  GenJet:
    pt: 8 
    eta: 10 
    
  Muon:
    pt: 20
    eta: 10
    id: tightId
    iso: 0.25

  Electron:
    pt: 15
    eta: 10
    iso: 0.06
    id: mvaIso_WP80