btagging:
  sampleGroups:
    ttH:
      sampleNames:
        - TTH_Hto2B
        - TTHtoNon2B
    ttbar:
      sampleNames:
        - TTTo2L2Nu
        - TTToLNu2Q
        - top
        - TTLL_ML_to50
        - TTLL_ML_50
        - TTNuNu
        - TTLNu
        - TTZ
        - TWminus
        - TWplus
    Vjets:
      sampleNames:
        - WJetsToLNu
        - ZZ
        - WW
        - WZ
        - DYJetsToLL
        - DYto2L-2Jets_MLL-10to50
        - DYto2L-2Jets_MLL-50
    HH4b_kl-1p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-1p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-m2p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-m2p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-m1p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-m1p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-5p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-5p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-2p45_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-2p45_kt-1p00_c2-0p00_skimmed
    HH4b_kl-0p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-0p00_kt-0p00_c2-0p00_skimmed
    HH4b_kl-3p50_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-3p50_kt-1p00_c2-0p00_skimmed
    HH4b_kl-4p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-4p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-3p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-3p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-2p00_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-2p00_kt-1p00_c2-0p00_skimmed
    HH4b_kl-1p50_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-1p50_kt-1p00_c2-0p00_skimmed
    HH4b_kl-0p50_kt-1p00:
      sampleNames:
        - GluGlutoHHto4B_spanet_kl-0p50_kt-1p00_c2-0p00_skimmed
