HLT_triggers:
  "2022_preEE":
    JetMET:
       - QuadPFJet70_50_40_35_PFBTagParticleNet_2BTagSum0p65
  "2022_postEE":
    JetMET:
       - QuadPFJet70_50_40_35_PFBTagParticleNet_2BTagSum0p65

## TRIGGERS FOR 2023 PARKING OR PRE PARKING STILL TO BE UNDERSTOOD
#   "2023_preBPix":
#     JetMET:
#        - HLT_QuadPFJet70_50_40_35_PNet2BTagMean0p65
#     ParkingHH:
#        - PFHT280_QuadPFJet30_PNet2BTagMean0p55
#   "2023_postBPix":
#     JetMET:
#        - HLT_QuadPFJet70_50_40_35_PNet2BTagMean0p65
#     ParkingHH:
#        - PFHT280_QuadPFJet30_PNet2BTagMean0p55

L1_triggers:
  "2022_preEE":
    JetMET:
       - HTT360er
      #  - Mu6_HTT240er
  "2022_postEE":
    JetMET:
       - HTT360er
      #  - Mu6_HTT240er

## TRIGGERS FOR 2023 PARKING OR PRE PARKING STILL TO BE UNDERSTOOD
#   "2023_preBPix":
#     JetMET:
#        - HTT360er
#     ParkingHH:
#        - HTT280er
#   "2023_postBPix":
#     JetMET:
#        - HTT360er
#     ParkingHH:
#        - HTT280er


